### ISSUE TITLE
Determine text extraction

### ISSUE THREAD

**Issue by swandog30** [Minitex/PDFKitTest#4]
Investigate copy test out of the pdf

**Comment by vuinguyen** [comment]
![img_0125](https://user-images.githubusercontent.com/1022275/31677491-2eaa6de0-b328-11e7-8b0a-6519b14e56ca.JPG)![img_0127](https://user-images.githubusercontent.com/1022275/31677494-30a86ffc-b328-11e7-8fe3-39ff105388d6.JPG)

There is a way to do copy to clipboard ("out of the box" for PDFKit) by doing a long press in the PDF document. Then, you can do a paste (in this example, into the Notes app) by doing a long press in the app you're copying into.

**Comment by vuinguyen** [comment]
The built-in functionality in iOS to do copy-paste is sufficient for meeting customers' needs for text extraction in PDF books. Closing this issue now.
